apiVersion: apps/v1
kind: Deployment
metadata:
  name: buyme-gateway-k8s
spec:
  selector:
    matchLabels:
      app: buyme-gateway-k8s
  replicas: 1
  template:
    metadata:
      labels:
        app: buyme-gateway-k8s
    spec:
      containers:
        - name: buyme-gateway-k8s
          image: buymemain/gateway:latest
          ports:
            - containerPort: 4000